name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git email
        run: git config --global user.email "$EMAIL"
        env:
          EMAIL : ${{ secrets.EMAIL }}
      - name: Setup git name
        run: git config --global user.name "$NAME"
        env:
          NAME : ${{ secrets.NAME }}
      - name: Clone gitlab repository
        run: git clone https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@git.hhu.de/jubok100/test
        env:
         GITLAB_TOKEN_NAME : ${{ secrets.GITLAB_TOKEN_NAME }}
         GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN}}
      - name: Navigate to correct folder
        run: cd test/testfolder/
      - name: Clone github repo
        run: git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/Inujal/github-actions-test-repo.git
        env:
         GITHUB_TOKEN : ${{ secrets.G_TOKEN }}
      - name: Check files
        run: ls -la
      - name: Check git
        run: git status
      - name: Navigate up
        run: cd ..
      - name: Check files
        run: ls -la
      - name: Check git
        run: git status
      - name: Git add
        run: git add .
      - name: Git commit
        run: git commit -m "📝 update stuff"
      - name: Push to gitlab
        run: git push https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@git.hhu.de/jubok100/test
        env:
         GITLAB_TOKEN_NAME : ${{ secrets.GITLAB_TOKEN_NAME }}
         GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN}}

