name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Clone gitlab repository
        run: git clone https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@git.hhu.de/jubok100/test
        env:
         GITLAB_TOKEN_NAME : ${{ secrets.GITLAB_TOKEN_NAME }}
         GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN}}
      - run: ls -la
      - run: cd test
      - uses: actions/checkout@v3
      - run: ls -la
      - run: cd ..
      - run: git add .
      - run: git commit -m "📝 update stuff"
      - run: git push https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@git.hhu.de/jubok100/test

